const BOT_ID = 'bot';

const FEED_OUTBOUND_MESSAGE_TYPE = 'FEED';
const USERS_OUTBOUND_MESSAGE_TYPE = 'USERS';

module.exports = {
  BOT_ID,
  FEED_OUTBOUND_MESSAGE_TYPE,
  USERS_OUTBOUND_MESSAGE_TYPE,
};
