const BOT_NAME = 'bot';

const QUESTION_INBOUND_MESSAGE_TYPE = 'QUESTION';
const ANSWER_INBOUND_MESSAGE_TYPE = 'ANSWER';

const FEED_OUTBOUND_MESSAGE_TYPE = 'FEED';
const USERS_OUTBOUND_MESSAGE_TYPE = 'USERS';

module.exports = {
  BOT_NAME,
  QUESTION_INBOUND_MESSAGE_TYPE,
  ANSWER_INBOUND_MESSAGE_TYPE,
  FEED_OUTBOUND_MESSAGE_TYPE,
  USERS_OUTBOUND_MESSAGE_TYPE,
};
